### ISSUE TITLE
Custom `assets` directory is ignored

### ISSUE THREAD

**Issue by janhohenheim** [kaosat-dev/Blender_bevy_components_workflow#137]
Didn't do a hard dive into this one, but at least the registry plugin uses a hardcoded path to `"assets/..."`. We should instead read the assets path from the `AssetPlugin`. For reference, this is how I did it for Yarn Spinner: https://github.com/YarnSpinnerTool/YarnSpinner-Rust/blob/v0.2.0/crates/bevy_plugin/src/plugin.rs#L245-L256

**Comment by kaosat-dev** [comment]
That would be a much better way of handling things indeed !
Will look into it once the release for v0.13 is done

**Comment by kaosat-dev** [comment]
Upon closer inspection, the only crate using a hardcoded path is the Registry plugin.
I remember adding it in that form because I am not sure the registry.json file is even an asset at all , since it is purely for dev purposes. In my earlier prototypes it was exported to the root of the app.
Not sure what makes the most sense in that context.

**Comment by janhohenheim** [comment]
I see your point. I'd use the assets directory of the AssetsPlugin still.

**Comment by kaosat-dev** [comment]
now implemented on bevy_main / v0.13 , and I hope you do not mind, I basically re-used your code with a few minor changes.
(Btw I saw how you are dealing with determining if change watcher is enabled, and that will soon-ish come very handy when I finally get around to adding hot-reloading to bevy_gltf_blueprints !)

**Comment by janhohenheim** [comment]
@kaosat-dev this is what open source is for :) I think you can take quite a bit of code from Yarn Spinner for the hot reloading part
