### ISSUE TITLE
Model with animation support?

### ISSUE THREAD

**Issue by katopz** [kaosat-dev/Blender_bevy_components_workflow#26]
Hi, Thanks for creating this. You're life saver!

BTW i'm not sure model with animation support?
Far as  I try rotation is broken somehow and maybe need a way to handle animation clip (and also manual rotate the turret later)

<img width="1783" alt="image" src="https://github.com/kaosat-dev/Blender_bevy_components_workflow/assets/97060/a571543f-8e77-498c-89ca-bd57f9dc384f">

The turret 3d model is here https://sketchfab.com/3d-models/missiletower-building002-9e0b1bcc84734c69a21e9c865fcfc172

Thanks again.

**Comment by kaosat-dev** [comment]
Hi @katopz ! 
Thanks for the kind words.
Very timely :) 
* I just noticed that rotation & scale are broken this afternoon (only for collection instances).
I am almost done with the fix (rotation works, for some weird reason, the scale does not get exported to the gltf files, still investigating). A new version of the Blender plugin & bevy_gltf_blueprints should be out in a few hours max
* There is some support for animations (a very small convenience wrapper around how the animations work in Bevy) , but I haven't explicitly mentioned it yet, as it is still work in progress. I'll try to post something about that a bit later.

**Comment by kaosat-dev** [comment]
@katopz , the issue with rotation & scaling is now resolved, please make sure to use the latest version of the Blender add-on :)
I'll ping you when I have some more things to share regarding animation

**Comment by katopz** [comment]
Thanks!

Turret base look in place now but other object gone wild.

<img width="2246" alt="image" src="https://github.com/kaosat-dev/Blender_bevy_components_workflow/assets/97060/58da4015-36a9-4950-a662-2f7153257e27">

and I can see a lot of output continuous yelling.
```
2023-10-15T02:04:21.155587Z  INFO bevy_gltf_components::process_gltfs: checking for loaded gltfs Unloaded
2023-10-15T02:04:21.171902Z  INFO bevy_gltf_components::process_gltfs: checking for loaded gltfs Unloaded
2023-10-15T02:04:21.172020Z  INFO bevy_gltf_components::process_gltfs: checking for loaded gltfs Unloaded
2023-10-15T02:04:21.188205Z  INFO bevy_gltf_components::process_gltfs: checking for loaded gltfs Unloaded
2023-10-15T02:04:21.188301Z  INFO bevy_gltf_components::process_gltfs: checking for loaded gltfs Unloaded
```

This yelling also happen before the fix i think (should be other issue).

Anyhow load the 3d model only to the scene also appear the same, 
maybe it's because the 3d model itself not playing nicely with Bevy.

I will try again with less complex 3d model to find the root cause. 🤔

**Comment by kaosat-dev** [comment]
It seems there are multiple issues going on at the same time:
* the model itself has issues for me , even in Blender, I had to forcefully rotate it by 90° to get it to work
* on your latest picture it looks like you have not exported the gltf file with the "Y-Up" option toggled
* I tried it with this model : https://sketchfab.com/3d-models/robot-courier-all-terrain-free-low-poly-model-2626b4a125ed4623936afc76c7a6483d and it seemed to work out of the box
 
![Screenshot from 2023-10-15 10-01-58](https://github.com/kaosat-dev/Blender_bevy_components_workflow/assets/623281/ba5db4f7-24c8-4685-8730-5441001c28de)

* the continuous "yelling" , means something is not normal when loading the gltf files, it seems Bevy is unloading the files before they are done loading completely, I need to check if that happens inside Bevy without the plugins too, because that a big issue

**Comment by kaosat-dev** [comment]
It seems the handles to the gltf assets are being dropped prematurely, still investigating.
I was working on some other improvements that I will push first, but i'll try to fix this asap

**Comment by kaosat-dev** [comment]
Hi @katopz I started investigating the issue in more details, sorry for the delay , could you please tell me 
- if you exported the scene using the standard Blender gltf exporter or the auto_gltf_exporter (the one in this repo?)
- you used the advanced example as a basis right ?
Thanks in advance :)

**Comment by katopz** [comment]
Hi, No worry for the delay just a hobby here :)

- yes and yes (v 0.3 at that time).
- yes.

Only diff now should be `y-up` (already set to `y-up` now) when export and `bevy 0.11.3` (have to lock at `0.11.3` or crash due to https://github.com/bevyengine/bevy/issues/9389 )

<img width="553" alt="image" src="https://github.com/kaosat-dev/Blender_bevy_components_workflow/assets/97060/0f0dfd7f-a3f5-4ed1-b9ea-a5515dd93861">

I can understand about `gltf` limitation (vary import/export), 
maybe we need the working animation examples and precise config.
The model itself can be and fix and modify  in blender to match our requirements/config anyhow.

btw i try `0.5` but can't trigger auto export after modify and save anymore not sure how i can manually export (as i recall it should auto export for me am i right?)

Thanks!

**Comment by mlflabs** [comment]
Could you provide simple code example how to get animations playing?

**Comment by kaosat-dev** [comment]
@katopz &  @mlflabs I am currently fixing a small issue ,improving the API and adding an example for animations, I'll let you know once it is ready. Because of the Bevy issue #29 that is fixed in V0.12, it is a bit complicated , as most of my test models with animations get unloaded wildly haha.

@katopz thanks for the details :)
Yes auto-export is the best way (and the only way to use Blueprints easilly).
I upgraded/improved the UI/UX of the Blender addon, if you have issues with that part, please open an issue for it :)

**Comment by kaosat-dev** [comment]
@katopz & @mlflabs I just released a new version of ```bevy_gltf_blueprints``` with animation support & example :)
you can check out the example here : https://github.com/kaosat-dev/Blender_bevy_components_workflow/tree/main/examples/animation, particularly [this part](https://github.com/kaosat-dev/Blender_bevy_components_workflow/blob/main/examples/animation/game/in_game.rs#L87)  on how to trigger/control animations (it is standard Bevy with an extra helper I added to make things a bit simpler .

Additional fyi for you @katopz , it works really well with the latest version of the Blender Addon, so if you have issues/questions for that, please do not hesitate :)

Have fun !

**Comment by katopz** [comment]
Thanks! @kaosat-dev This should be fun! I'll get back to try this after I'm done with llm.

Anyway I owed you a beer! Do ping [me](https://twitter.com/katopz) if you come to Bangkok. :)

**Comment by kaosat-dev** [comment]
Haha thank you , and gladly @katopz :) Never been there before, would love to visit one day ;)
