### ISSUE TITLE
RigidBodyProxy redundant

### ISSUE THREAD

**Issue by GitGhillie** [kaosat-dev/Blender_bevy_components_workflow#6]
https://github.com/kaosat-dev/Blender_bevy_components_worklflow/blob/528e13a250f38f786b18771b7b9a9638d1909d94/examples/basic/core/physics/physics_replace_proxies.rs#L11C1-L17C2

Correct me if I'm wrong but `RigidBodyProxy` (also in advanced example) is not necessary anymore. RigidBody will do the trick.
Are you open to PRs by the way?

**Comment by kaosat-dev** [comment]
Hi @GitGhillie ! yes I am open to PRs :)
Last time I tried (it was a while back though, so it is totally possible it works now) getting rid of RigidBodyProxy & using RigidBody directly I still ran into weird issues.
If you manage to get rid of that , a PR would be very welcome :+1:

**Comment by GitGhillie** [comment]
Cool!
I opened the examples and noticed that it looks like you are already not using RigidBodyProxy on the objects.
What is the weird issues you had roughly? I did notice that the teapot for example will sometimes shoot off into the sky.

**Comment by kaosat-dev** [comment]
I double checked and you are completely right, RigidBodyProxy is not used anymore, and could be removed
* one of weird issues that I had (but that is quite a lot of commits ago, not entirely sure about it), was that the RigidBody alone was not working as expected , though that was with an older version of `bevy_rapier` so I think it is safe to remove those proxies now
* the teapot has a **Mesh** collider, from a low poly sphere, instead of a SphereCollider (to keep it simple for demo purposes), so not too surprised that physics are wonky :)

**Comment by GitGhillie** [comment]
Alright thx for confirming, I will prepare a PR 😄
